In [1]:
import numpy as np
np.random.seed(0) # Randomness locked at specific 

In [8]:
# Use reshape to turn a single dimensional to multi
grid = np.arange(1,10).reshape((3 , 3))

print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [15]:
x.reshape((1,3)) # Same Output

array([[1, 2, 3]])

In [20]:
# Reshaping without using positional index
x.reshape((3 , 1))

array([[1],
       [2],
       [3]])

In [40]:
np.random.seed(0)
# Joining arrays without using for loop

x1 = np.array([1,2,3])
y1 = np.array([5,2,3]) # [3, 2, 1]
z1 = np.array([6 , 6 , 6 ])

# you can try concatenate for that.
np.concatenate([x1 , y1 , z1])

array([1, 2, 3, 5, 2, 3, 6, 6, 6])

In [43]:
# Going overboard with concatenate
# Always remember to use a 3rd bracket as well

np.concatenate([grid, grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# CONCATENATE WITH AXIS?
np.concatenate([grid, grid, grid], axis=1)
# Axis breaks a 3 row 9 columns to 9 rows 3 columns

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [48]:
# Joining a single dimensional with multi 
# Use vstack to vertically stack 
# arrays are added to the columns

x2 = np.array([1 , 2 , 3])
y2 = np.array([[1 , 2 , 3],
               [4 , 5 , 6]])
np.vstack([x2 , y2])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
# You can use hshift to horizontaly stack them
# Arrays are added to the rows
y3 = [[99],
      [99]]
# np.hstack([grid, y3])
# HUH?
gridNEW = np.arange(1, 7).reshape(2,3)
gridNEW

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# Splitting an array
# Finding the mid-point of an array
# EX_1 = array([1, 2, 3, 5, 2, 3, 6, 6, 6])

EX_1 = np.concatenate([x1 , y1 , z1])
# Using the positional indexes
ex1, mid-point, ex3 = np.split(EX_1 , [4,5]) 
print(ex1, mid-point, ex3)

[1 2 3 5] [2] [3 6 6 6]


In [86]:
# Arrange the split in vertical
# works on arrays of multi-dimensional

grid = np.arange(16).reshape(4 , 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
# variable now contains two arrays
splited = np.vsplit(grid , [2])
splited

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [99]:
# Assigning the values to the separate variables
split_1 , split_2 = splited
print(split_1)
print(split_2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [101]:
split_3 , split_4 = np.hsplit(grid, [2])
print(split_3)
print(split_4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
