In [1]:
import numpy as np

In [2]:
# Creating a 3x5 array that contains only 3.14
np.full((3 , 5) , 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# Creating a list where the even numbers of 0 to 20 exists
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Creating a list where the odd numbers of 0 to 20 exists
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
# Creating a list from 0 to 1 at 5 integers gap?
# Answer is set at float dtype?
np.linspace(0 , 1 , 5 , dtype="float") # (start , end , interval?)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Creating an array of 0 and 1 in a 3x3 dimension array
np.random.random((3 , 3))

array([[0.23773503, 0.10234718, 0.89448916],
       [0.8473527 , 0.76822811, 0.58171216],
       [0.24091232, 0.27020547, 0.88310643]])

In [32]:
np.random.normal(0 , 1 , (3 , 3))

array([[-0.27779323,  0.26276931,  0.18901163],
       [-2.16760503,  0.51193415, -0.09424928],
       [ 0.76619148,  0.80810499, -0.17689538]])

In [33]:
# (start , finish , (rows , columns))
np.random.randint(0 , 10 , (3 , 3))

array([[3, 9, 8],
       [7, 3, 9],
       [4, 0, 4]])

In [38]:
np.eye(3)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])