In [1]:
import numpy as np

In [30]:
np.random.seed(0) # seed for reproducibility

# creating dimensions
# syntax(first , last, size(dimension , dimension , dimension))

x2 = np.random.randint(0 , 10, size=(4 , 4))

print(x2)

print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size) # dimension x dimension == array.size

# use ndim to find number of dimension
# use shape to find the size of each of the dimension
# use size to find the total size of each of the dimension

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
x2 ndim:  2
x2 shape: (4, 4)
x2 size:  16


In [31]:
# trying to know the data type?
# try this!
print("dtype : " , x2.dtype)

dtype :  int32


In [32]:
# To find out the total size of the list or array, Try this!
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 64 bytes


In [46]:
# Change data inside an array using index!!
x2
# Change the 2nd int of the 3rd array to "25
x2[1, 2] = 25


# Warning!

# numpy.array has a fixed value type. changing it can lead to Error!
# =============== EXAMPLE =================
# Change the whole 2nd int of every array to "string"
# x2[null, 2] = "string"
# throws an error

In [6]:
import numpy as np

x1 = np.random.randint(0 , 10 , size=(6))
x1

array([0, 8, 4, 4, 2, 0])

x1[0] = 3.1416 # float, will be shorten

In [7]:
x1[0] = 3.1416 # float, will be shorten

In [8]:
x1[0]

3

In [9]:
x1

array([3, 8, 4, 4, 2, 0])

In [10]:
x1[:1] # elements before position 1

array([3])

In [11]:
x1[1:] # elemets after position 1

array([8, 4, 4, 2, 0])

In [12]:
Xnew = np.arange(10)
Xnew

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
Xnew[::-2] # Odd numbers starting at last int to first using a 2 interval

array([9, 7, 5, 3, 1])

In [20]:
# Goes reverse printing the array
Xnew[::-2] 
# At a 2 interval

array([9, 7, 5, 3, 1])

In [19]:
Xnew[::-1] # At a 1 interval

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
# REMEMBER - x[start:stop:step]
# DEMO
Xnew[5::-2]

array([5, 3, 1])

In [99]:
x3 = np.random.randint(0 , 10, size=(4 , 4))
np.random.seed(0)
x3

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]])

In [94]:
x3[:2] # 2 rows, OR rows from 1st to 2nd

array([[5, 0, 3, 3],
       [7, 9, 3, 5]])

In [95]:
x3[3 , 0] # On the 0th row of the 4th column

8

In [96]:
x3[1 , 2]

3

In [103]:
x3[0 , 2] = 4
x3[0]

array([4, 4, 4, 3])

In [107]:
x3[0]


array([4, 4, 4, 3])

In [121]:
x3[0 , 2:4]

array([4, 3])

In [122]:
x3

array([[4, 4, 4, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]])

In [163]:
x3[:4 , 0::4] 
# Arrange array towards the 4th row starting at the 1st column

array([[4],
       [7],
       [2],
       [8]])

In [166]:
x3[:4 , 2::3] 

array([[4],
       [3],
       [7],
       [1]])

In [168]:
x3[0] # log without print

array([4, 4, 4, 3])

In [169]:
print(x3[0]) # Log with print

[4 4 4 3]


In [170]:
print(x3)

[[4 4 4 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]


In [171]:
x3[:2 , :2]

array([[4, 4],
       [7, 9]])

In [173]:
x3_sub_copy = x3[:2 , :2].copy()
print(x3_sub_copy) # Copy?

[[4 4]
 [7 9]]
