In [1]:
import numpy as np
np.random.seed(0)

In [2]:
values = np.random.randint(1,10,size=5)

In [3]:
values

array([6, 1, 4, 4, 8])

In [9]:
# returns without entries
# dtype = float
np.empty(len(values))

array([2.12199579e-314, 2.48273508e-312, 4.16991405e-321, 3.79442416e-321,
       0.00000000e+000])

In [5]:
import numpy as np
# Finding the reciprocals of the entries
def reciprocals(val):
    output = np.empty(len(val) # See Out[9]
    for i in range(len(val)):
        output[i] = 1.0/val[i]
    return output



values = np.random.randint(1,10,size=5)
reciprocals(values)

array([0.2       , 0.14285714, 0.16666667, 0.25      , 0.11111111])

In [9]:
print(reciprocals(values)) # function
print(1/values) # no function

[0.2        0.14285714 0.16666667 0.25       0.11111111]
[0.2        0.14285714 0.16666667 0.25       0.11111111]


In [19]:
# Exploring ufuncs and numpy operators
x = np.arange(4)
print("x     = " , x)       # Normal
print("x + 5 = " , x + 5)   # Starting at 5
print("x - 3 = " , x - 3)   # Starting at -3
print("x * 2 = " , x * 2)   # Starting at 0 and increase 2 times
print("x / 2 = " , x / 2)   # Starting at 0 and prints the 1/2 of the numbers
print("x // 2 = " , x // 2) # Starting at 0 and shows the floor division of 2
print("-x    = " , -x)      # Instructing the array to reverse 
print("x ** 2 = ", x ** 2)  # Power of 2 [exponentiation]
print("x % 2 = " , x % 2)   # Percentage of 2 

x     =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 3 =  [-3 -2 -1  0]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [22]:
np.add(x, 2)  # Number starting at 2
print(x + 2 ) # Number starting at 2

[2 3 4 5]


In [23]:
# Using numpy absolute value [abs]
x1 = [-5 , -6, -2, -5, -7, -9]
np.absolute(x1)

array([5, 6, 2, 5, 7, 9])

In [30]:
# Trigometric supported

theta = np.linspace(0 , np.pi , 3)

print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))      # sin theta
print("cos(theta) = ", np.cos(theta))      # cos theta
print("tan(theta) = ", np.tan(theta))      # tan theta

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [28]:
print(theta)

[0.         1.57079633 3.14159265]


In [29]:
print(np.pi) # Shows the pi

3.141592653589793


In [34]:
x = np.arange(5) # 0 1 2 3 4
print("x =", x)
print("e^x =", np.exp(x)) # No power
print("2^x =", np.exp2(x)) # 2^x
print("3^x =", np.power(3, x)) # 3^x


x = [0 1 2 3 4]
e^x = [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
2^x = [ 1.  2.  4.  8. 16.]
3^x = [ 1  3  9 27 81]


In [39]:
# Logorithm supported
# np.log(x) or np.ln(x)
x = [1 , 2 , 3]
print("x       = " , x)
print("log(x) = " , np.log(x))
print("log2(x) = " , np.log2(x))
print("log(1 + x) = "  , np.log1p(x))


x       =  [1, 2, 3]
log(x) =  [0.         0.69314718 1.09861229]
log2(x) =  [0.        1.        1.5849625]
log(1 + x) =  [0.69314718 1.09861229 1.38629436]


In [42]:
# Find the exponential value
print("exp(x) - 1 = " , np.expm1(x)) # exponential of x minus 1[expm1]
print("log(x) + 1 = " , np.log1p(x)) # logorithm of x plus 1

exp(x) - 1 =  [ 1.71828183  6.3890561  19.08553692]
log(x) + 1 =  [0.69314718 1.09861229 1.38629436]
